//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("")
export class Entity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
: string;

@Column({nullable: true})
: string;

@Column({nullable: true})
: string;

@Column({nullable: true})
: string;

@Column({nullable: true})
: string;

@Column({nullable: true})
: string;

@Column({nullable: true})
: string;


}
