//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("albums")
export class albumsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
albumName: string;

@Column("integer",{nullable: true})
artistName: number;

@Column("integer",{nullable: true})
copiesSold: number;

@Column("date",{nullable: true})
launchDate: Date;


}
