//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("artists")
export class artistsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
artistName: string;

@Column("text",{nullable: true})
band: string;

@Column("date",{nullable: true})
dateOfBirth: Date;


}
