//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Authors")
export class AuthorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
authorName: string;

@Column({nullable: true})
dateOfBirth: string;

@Column({nullable: true})
gender: string;

@Column({nullable: true})
countryOfBirth: string;


}
