//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("authors")
export class authorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
name: number;

@Column({nullable: true})
gender: number;

@Column({nullable: true})
dateOfBirth: number;

@Column({nullable: true})
numberOfBooks: number;


}
