//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("authors")
export class authorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
authorName: string;

@Column({nullable: true})
dateOfBirth: Date;

@Column({nullable: true})
sex: string;

@Column({nullable: true})
countryOfBirth: string;


}
