//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("books")
export class booksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
bookTitle: string;

@Column({nullable: true})
releaseDate: Date;

@Column({nullable: true})
numberOfBooksSold: number;

@Column({nullable: true})
author: string;

@Column({nullable: true})
numberOfEditions: number;


}
