//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Books")
export class BooksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
bookTitle: string;

@Column({nullable: true})
releaseDate: string;

@Column({nullable: true})
numberOfBooksSold: string;

@Column({nullable: true})
author: string;

@Column({nullable: true})
numberOfEditions: string;


}
