//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("contacts")
export class contactsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
name: string;

@Column("text",{nullable: true})
mobile: string;

@Column("text",{nullable: true})
email: string;


}
