//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("credentials")
export class credentialsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
url: string;

@Column("text",{nullable: true})
username: string;

@Column("text",{nullable: true})
password: string;


}
