//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Discounts")
export class DiscountsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
productId: number;

@Column({nullable: true})
discountName: string;

@Column({nullable: true})
description: string;

@Column({nullable: true})
discountAmount: number;

@Column({nullable: true})
discountPercent: number;


}
