//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Employees")
export class EmployeesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
employeeId: string;

@Column({nullable: true})
firstName: string;

@Column({nullable: true})
lastName: string;

@Column({nullable: true})
middleName: string;

@Column({nullable: true})
dateOfBirth: Date;

@Column({nullable: true})
gender: string;

@Column({nullable: true})
nationality: string;

@Column({nullable: true})
maritalStatus: string;

@Column({nullable: true})
email: string;

@Column({nullable: true})
phoneNumber: string;

@Column({nullable: true})
street: string;

@Column({nullable: true})
city: string;

@Column({nullable: true})
state: string;

@Column({nullable: true})
zipCode: string;

@Column({nullable: true})
country: string;

@Column({nullable: true})
departmentTeam: string;

@Column({nullable: true})
positionRole: string;

@Column({nullable: true})
managerSupervisor: string;

@Column({nullable: true})
employmentType: string;

@Column({nullable: true})
startDate: Date;

@Column({nullable: true})
endDate: Date;

@Column({nullable: true})
salaryInformation: number;

@Column({nullable: true})
profilePicture: string;


}
