//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Evaluations")
export class EvaluationsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
reviewId: string;

@Column({nullable: true})
employeeId: number;

@Column({nullable: true})
periodStartDate: Date;

@Column({nullable: true})
periodEndDate: Date;

@Column({nullable: true})
goalsObjectives: string;

@Column({nullable: true})
achievements: string;

@Column({nullable: true})
improvementAreas: string;

@Column({nullable: true})
feedbackFromSupervisor: string;

@Column({nullable: true})
overallRating: number;

@Column({nullable: true})
recommendations: string;


}
