//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("friends")
export class friendsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
name: string;

@Column("date",{nullable: true})
birthday: Date;

@Column("text",{nullable: true})
starSign: string;

@Column("text",{nullable: true})
gender: string;

@Column("text",{nullable: true})
email: string;


}
