//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Loans")
export class LoansEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
accountNumber: string;

@Column({nullable: true})
loanAmount: string;

@Column({nullable: true})
productType: string;

@Column({nullable: true})
outstandingBalance: string;


}
