//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Orders")
export class OrdersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
orderId: string;

@Column({nullable: true})
customerId: number;

@Column({nullable: true})
totalAmount: number;

@Column({nullable: true})
vat: number;

@Column({nullable: true})
productTotalAmount: number;

@Column({nullable: true})
shippingCost: number;

@Column({nullable: true})
shippingAddress: string;

@Column({nullable: true})
orderAddress: string;

@Column({nullable: true})
orderEmail: string;

@Column({nullable: true})
orderDate: Date;

@Column({nullable: true})
orderStatus: string;

@Column({nullable: true})
trackingNo: string;


}
