//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("OrderDetails")
export class OrderDetailsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
orderId: number;

@Column({nullable: true})
productId: number;

@Column({nullable: true})
price: number;

@Column({nullable: true})
quantity: number;


}
