//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Payments")
export class PaymentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
paymentId: string;

@Column({nullable: true})
orderId: number;

@Column({nullable: true})
amount: number;

@Column({nullable: true})
paymentMethod: string;

@Column({nullable: true})
paymentDate: Date;

@Column({nullable: true})
paymentStatus: string;


}
