//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Payroll")
export class PayrollEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
payrollId: string;

@Column({nullable: true})
employeeId: number;

@Column({nullable: true})
periodStartDate: Date;

@Column({nullable: true})
periodEndDate: Date;

@Column({nullable: true})
grossSalary: number;

@Column({nullable: true})
deductions: string;

@Column({nullable: true})
netSalary: number;

@Column({nullable: true})
payDate: Date;

@Column({nullable: true})
overtimeHours: number;

@Column({nullable: true})
overtimePay: number;


}
