//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("ProductCategories")
export class ProductCategoriesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
categoryId: string;

@Column({nullable: true})
productId: number;

@Column({nullable: true})
description: string;


}
