//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("RealEstate")
export class RealEstateEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
propertyType: string;

@Column({nullable: true})
value: string;

@Column({nullable: true})
location: string;

@Column({nullable: true})
floodRisk: string;

@Column({nullable: true})
earthquakeRisk: string;

@Column({nullable: true})
fireRisk: string;

@Column({nullable: true})
geolocation: string;


}
