//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("RiskFactors")
export class RiskFactorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
riskFactor: string;

@Column({nullable: true})
riskWeight: string;


}
