//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Tasks")
export class TasksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
taskName: string;

@Column({nullable: true})
description: string;

@Column({nullable: true})
dueDate: string;

@Column({nullable: true})
status: string;

@Column({nullable: true})
priority: string;

@Column({nullable: true})
assigneeName: string;

@Column({nullable: true})
projectName: string;


}
