//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("tasks")
export class tasksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
taskTitle: string;

@Column("text",{nullable: true})
description: string;

@Column("date",{nullable: true})
scheduledStartDate: Date;

@Column("date",{nullable: true})
scheduledEndDate: Date;

@Column("date",{nullable: true})
actualEndDate: Date;


}
