//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Vendors")
export class VendorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
vendorId: string;

@Column({nullable: true})
companyName: string;

@Column({nullable: true})
contactName: string;

@Column({nullable: true})
email: string;

@Column({nullable: true})
password: string;


}
